DICO_COULEUR = {'alice blue':'bleu',
            'antique white':'beige',
            'AntiqueWhite1':'beige',
            'AntiqueWhite2':'beige',
            'AntiqueWhite3':'marron',
            'AntiqueWhite4':'marron',
            'aquamarine':'bleu',
            'aquamarine2':'turquoise',
            'aquamarine4':'turquoise',
            'azure':'bleu',
            'azure2':'bleu',
            'azure3':'bleu',
            'azure4':'bleu',
            'beige':'blanc',
            'bisque':'beige',
            'bisque2':'orange',
            'bisque3':'marron',
            'bisque4':'marron',
            'black':'noir',
            'blanched almond':'beige',
            'blue':'bleu',
            'blue violet':'bleu',
            'blue2':'bleu',
            'blue4':'bleu',
            'brown':'rouge',
            'brown1':'rouge',
            'brown2':'rouge',
            'brown3':'rouge',
            'brown4':'rouge',
            'burlywood':'beige',
            'burlywood1':'beige',
            'burlywood2':'beige',
            'burlywood3':'beige',
            'burlywood4':'marron',
            'cadet blue':'bleu',
            'CadetBlue1':'bleu',
            'CadetBlue2':'bleu',
            'CadetBlue3':'bleu',
            'CadetBlue4':'bleu',
            'chartreuse':'vert',
            'chartreuse2':'vert',
            'chartreuse3':'vert',
            'chartreuse4':'vert',
            'chocolate':'orange',
            'chocolate1':'orange',
            'chocolate2':'orange',
            'chocolate3':'orange',
            'coral':'orange',
            'coral1':'orange',
            'coral2':'orange',
            'coral3':'orange',
            'coral4':'marron',
            'cornflower blue':'bleu',
            'cornsilk':'blanc',
            'cornsilk2':'blanc',
            'cornsilk3':'gris',
            'cornsilk4':'kaki',
            'cyan':'bleu',
            'cyan2':'bleu',
            'cyan3':'bleu',
            'cyan4':'vert',
            'dark goldenrod':'marron',
            'dark green':'vert',
            'dark grey':'gris',
            'dark khaki':'kaki',
            'dark olive green':'vert',
            'dark orange':'orange',
            'dark orchid':'violet',
            'dark salmon':'beige',
            'dark sea green':'vert',
            'dark slate blue':'bleu',
            'dark slate gray':'gris',
            'dark turquoise':'bleu',
            'dark viole':'violet',
            'DarkGoldenrod1':'jaune',
            'DarkGoldenrod2':'jaune',
            'DarkGoldenrod3':'jaune',
            'DarkGoldenrod4':'marron',
            'DarkOliveGreen1':'vert',
            'DarkOliveGreen2':'vert',
            'DarkOliveGreen3':'vert',
            'DarkOliveGreen4':'vert',
            'DarkOrange1':'orange',
            'DarkOrange2':'orange',
            'DarkOrange3':'orange',
            'DarkOrange4':'marron',
            'DarkOrchid1':'violet',
            'DarkOrchid2':'violet',
            'DarkOrchid3':'violet',
            'DarkOrchid4':'violet',
            'DarkSeaGreen1':'vert',
            'DarkSeaGreen2':'vert',
            'DarkSeaGreen3':'vert',
            'DarkSeaGreen4':'vert',
            'DarkSlateGray1':'turquoise',
            'DarkSlateGray2':'bleu',
            'DarkSlateGray3':'bleu',
            'DarkSlateGray4':'vert',
            'deep pink':'rose',
            'deep sky blue':'bleu',
            'DeepPink2':'rose',
            'DeepPink3':'rose',
            'DeepPink4':'rouge',
            'DeepSkyBlue2':'bleu',
            'DeepSkyBlue3':'bleu',
            'DeepSkyBlue4':'bleu',
            'dim gray':'gris',
            'dodger blue':'bleu',
            'DodgerBlue2':'bleu',
            'DodgerBlue3':'bleu',
            'DodgerBlue4':'bleu',
            'firebrick':'rouge',
            'firebrick1':'rouge',
            'firebrick2':'rouge',
            'firebrick3':'rouge',
            'firebrick4':'rouge',
            'floral white':'blanc',
            'forest green':'vert',
            'gainsboro':'gris',
            'ghost white':'blanc',
            'gold':'jaune',
            'gold2':'jaune',
            'gold3':'jaune',
            'gold4':'kaki',
            'goldenrod':'jaune',
            'goldenrod1':'jaune',
            'goldenrod2':'jaune',
            'goldenrod3':'jaune',
            'goldenrod4':'marron',
            'gray':'gris',
            'gray1':'noir',
            'gray10':'noir',
            'gray11':'noir',
            'gray12':'noir',
            'gray13':'noir',
            'gray14':'noir',
            'gray15':'noir',
            'gray16':'noir',
            'gray17':'noir',
            'gray18':'noir',
            'gray19':'noir',
            'gray2':'noir',
            'gray20':'noir',
            'gray21':'noir',
            'gray22':'noir',
            'gray23':'gris',
            'gray24':'gris',
            'gray25':'gris',
            'gray26':'gris',
            'gray27':'gris',
            'gray28':'gris',
            'gray29':'gris',
            'gray3':'noir',
            'gray30':'gris',
            'gray31':'gris',
            'gray32':'gris',
            'gray33':'gris',
            'gray34':'gris',
            'gray35':'gris',
            'gray36':'gris',
            'gray37':'gris',
            'gray38':'gris',
            'gray39':'gris',
            'gray4':'noir',
            'gray40':'gris',
            'gray42':'gris',
            'gray43':'gris',
            'gray44':'gris',
            'gray45':'gris',
            'gray46':'gris',
            'gray47':'gris',
            'gray48':'gris',
            'gray49':'gris',
            'gray5':'noir',
            'gray50':'gris',
            'gray51':'gris',
            'gray52':'gris',
            'gray53':'gris',
            'gray54':'gris',
            'gray55':'gris',
            'gray56':'gris',
            'gray57':'gris',
            'gray58':'gris',
            'gray59':'gris',
            'gray6':'noir',
            'gray60':'gris',
            'gray61':'gris',
            'gray62':'gris',
            'gray63':'gris',
            'gray64':'gris',
            'gray65':'gris',
            'gray66':'gris',
            'gray67':'gris',
            'gray68':'gris',
            'gray69':'gris',
            'gray7':'noir',
            'gray70':'gris',
            'gray71':'gris',
            'gray72':'gris',
            'gray73':'gris',
            'gray74':'gris',
            'gray75':'gris',
            'gray76':'gris',
            'gray77':'gris',
            'gray78':'gris',
            'gray79':'gris',
            'gray8':'noir',
            'gray80':'gris',
            'gray81':'gris',
            'gray82':'gris',
            'gray83':'gris',
            'gray84':'gris',
            'gray85':'gris',
            'gray86':'gris',
            'gray87':'gris',
            'gray88':'gris',
            'gray89':'gris',
            'gray9':'noir',
            'gray90':'gris',
            'gray91':'gris',
            'gray92':'gris',
            'gray93':'gris',
            'gray94':'gris',
            'gray95':'blanc',
            'gray96':'blanc',
            'gray97':'blanc',
            'gray98':'blanc',
            'gray99':'blanc',
            'green':'vert',
            'green yellow':'vert', 
            'green2':'vert', 
            'green3':'vert', 
            'green4':'vert', 
            'honeydew':'blanc', 
            'honeydew2':'vert', 
            'honeydew3':'vert', 
            'honeydew4':'vert', 
            'hot pink':'rose', 
            'HotPink1':'rose', 
            'HotPink2':'rose', 
            'HotPink3':'rose', 
            'HotPink4':'rose', 
            'indian red':'rouge',
            'IndianRed1':'rouge', 
            'IndianRed2':'rouge', 
            'IndianRed3':'rouge', 
            'IndianRed4':'rouge', 
            'ivory':'blanc', 
            'ivory2':'beige', 
            'ivory3':'gris', 
            'ivory4':'gris', 
            'khaki':'jaune', 
            'khaki1':'jaune', 
            'khaki2':'jaune', 
            'khaki3':'jaune', 
            'khaki4':'kaki', 
            'lavender':'bleu', 
            'lavender blush':'rose', 
            'LavenderBlush2':'rose', 
            'LavenderBlush3':'gris', 
            'LavenderBlush4':'gris', 
            'lawn green':'vert', 
            'lemon chiffon':'blanc', 
            'LemonChiffon2':'jaune', 
            'LemonChiffon3':'kaki', 
            'LemonChiffon4':'kaki', 
            'light blue':'',
            'light coral':'bleu', 
            'light cyan':'rouge',
            'light goldenrod':'jaune',
            'light goldenrod yellow':'blanc',
            'light grey':'gris',  
            'light pink':'rose', 
            'light salmon': 'orange', 
            'light sea green':'bleu', 
            'light sky blue':'bleu', 
            'light slate blue':'bleu', 
            'light slate gray':'bleu',     
            'light steel blue':'bleu', 
            'light yellow': 'blanc',  
            'LightBlue1':'bleu', 
            'LightBlue2':'bleu', 
            'LightBlue3':'bleu', 
            'LightBlue4':'bleu', 
            'LightCyan2':'bleu', 
            'LightCyan3':'bleu', 
            'LightCyan4':'kaki', 
            'LightGoldenrod1':'jaune', 
            'LightGoldenrod2':'jaune', 
            'LightGoldenrod3':'jaune', 
            'LightGoldenrod4':'kaki', 
            'LightPink1':'rose', 
            'LightPink2':'rose', 
            'LightPink3':'rose', 
            'LightPink4':'rouge', 
            'LightSalmon2':'orange',
            'LightSalmon3':'orange',
            'LightSalmon4':'marron',
            'LightSkyBlue1':'bleu',
            'LightSkyBlue2':'bleu',
            'LightSkyBlue3':'bleu',
            'LightSkyBlue4':'bleu',
            'LightSteelBlue1':'bleu',
            'LightSteelBlue2':'bleu',
            'LightSteelBlue3':'bleu',
            'LightSteelBlue4':'bleu',
            'LightYellow2':'beige', 
            'LightYellow3':'kaki', 
            'LightYellow4':'kaki', 
            'lime green':'vert',
            'linen':'beige', 
            'magenta':'magenta',
            'magenta2':'magenta',
            'magenta3':'magenta',
            'magenta4':'violet',
            'maroon':'rouge',
            'maroon1':'rouge',
            'maroon2':'rouge',
            'maroon3':'rouge',
            'maroon4':'rouge',
            'medium aquamarine':'vert',
            'medium blue':'bleu',
            'medium orchid':'rose',
            'medium purple':'violet',
            'medium sea green':'vert',
            'medium slate blue':'bleu',
            'medium spring green':'vert',
            'medium turquoise':'bleu',
            'medium violet red':'rouge',
            'MediumOrchid1':'rose',
            'MediumOrchid2':'violet',
            'MediumOrchid3':'violet',
            'MediumOrchid4':'violet',
            'MediumPurple1':'violet',
            'MediumPurple2':'violet',
            'MediumPurple3':'bleu',
            'MediumPurple4':'bleu', 
            'midnight blue':'bleu',
            'misty rose':'rose',
            'MistyRose2':'rose',
            'MistyRose3':'marron',
            'MistyRose4':'marron',
            'moccasin':'beige',
            'navajo white':'beige',
            'NavajoWhite2':'beige',
            'NavajoWhite3':'beige',
            'NavajoWhite4':'marron,',
            'navy':'bleu',
            'old lace':'beige',
            'olive drab':'vert',
            'OliveDrab1':'vert',
            'OliveDrab2':'vert',
            'OliveDrab4':'vert',
            'orange':'orange',
            'orange red':'rouge',
            'orange2':'jaune',
            'orange3':'orange',
            'orange4':'orange',
            'OrangeRed2':'orange',
            'OrangeRed3':'marron',
            'OrangeRed4':'marron',
            'orchid':'rose',
            'orchid1':'rose',
            'orchid2':'rose',
            'orchid3':'rose',
            'orchid4':'violet',
            'pale goldenrod':'jaune',
            'pale green':'vert',
            'pale turquoise':'bleu',
            'pale violet red':'rose',
            'PaleGreen1':'vert',
            'PaleGreen2':'vert',
            'PaleGreen3':'vert',
            'PaleGreen4':'vert',
            'PaleTurquoise1':'bleu',
            'PaleTurquoise2':'bleu',
            'PaleTurquoise3':'bleu',
            'PaleTurquoise4':'bleu',
            'PaleVioletRed1':'rose',
            'PaleVioletRed2':'rose',
            'PaleVioletRed3':'rose',
            'PaleVioletRed4':'violet',
            'papaya whip':'blanc',
            'peach puff':'beige',
            'PeachPuff2':'beige',
            'PeachPuff3':'marron',
            'PeachPuff4':'marron',
            'peru':'orange',
            'pink':'rose',
            'pink1':'rose',
            'pink2':'rose',
            'pink3':'rose',
            'pink4':'marron',
            'plum':'violet',
            'plum1':'rose',
            'plum2':'rose',
            'plum3':'violet',
            'plum4':'violet',
            'powder blue':'bleu',
            'purple':'violet',
            'purple1':'violet',
            'purple2':'violet',
            'purple3':'violet',
            'purple4':'violet',
            'red':'rouge',
            'red2':'rouge',
            'red3':'rouge',
            'red4':'rouge',
            'rosy brown':'marron',
            'RosyBrown1':'rose',
            'RosyBrown2':'rose',
            'RosyBrown3':'marron',
            'RosyBrown4':'marron',
            'royal blue':'bleu',
            'RoyalBlue1':'bleu',
            'RoyalBlue2':'bleu',
            'RoyalBlue3':'bleu',
            'mint cream':'bleu',
            'RoyalBlue4':'bleu',
            'saddle brown':'marron',
            'salmon':'orange',
            'salmon1':'orange',
            'salmon2':'orange',
            'salmon3':'orange',
            'salmon4':'orange',
            'sandy brown':'',
            'sea green':'vert',
            'SeaGreen1':'vert',
            'SeaGreen2':'vert',
            'SeaGreen3':'vert',
            'seashell':'beige',
            'seashell2':'beige',
            'seashell3':'gris',
            'seashell4':'gris',
            'sienna':'marron',
            'sienna1':'orange',
            'sienna2':'orange',
            'sienna3':'orange',
            'sienna4':'marron',
            'sky blue':'bleu',
            'SkyBlue1':'bleu',
            'SkyBlue2':'bleu', 
            'SkyBlue3':'bleu', 
            'SkyBlue4':'bleu', 
            'slate blue':'bleu', 
            'slate gray':'bleu', 
            'SlateBlue1':'bleu', 
            'SlateBlue2':'bleu', 
            'SlateBlue3':'bleu', 
            'SlateBlue4':'bleu', 
            'SlateGray1':'bleu', 
            'SlateGray2':'bleu', 
            'SlateGray3':'bleu', 
            'SlateGray4':'bleu', 
            'snow':'blanc',
            'snow2':'gris', 
            'snow3':'gris', 
            'snow4':'gris', 
            'spring green':'vert',
            'SpringGreen2':'', 
            'SpringGreen3':'vert', 
            'SpringGreen4':'vert', 
            'steel blue':'bleu', 
            'SteelBlue1':'bleu', 
            'SteelBlue2':'bleu', 
            'SteelBlue3':'bleu', 
            'SteelBlue4':'bleu', 
            'tan':'beige', 
            'tan1':'marron', 
            'tan2':'marron', 
            'tan4':'marron', 
            'thistle':'violet', 
            'thistle1':'rose', 
            'thistle2':'violet', 
            'thistle3':'violet', 
            'thistle4':'violet', 
            'tomato':'orange', 
            'tomato2':'orange', 
            'tomato3':'orange', 
            'tomato4':'marron', 
            'turquoise':'turquoise', 
            'turquoise1':'turquoise', 
            'turquoise2':'turquoise', 
            'turquoise3':'turquoise', 
            'turquoise4':'turquoise', 
            'violet':'violet', 
            'violet red':'violet', 
            'VioletRed1':'violet', 
            'VioletRed2':'violet', 
            'VioletRed3':'violet', 
            'VioletRed4':'violet', 
            'wheat':'beige', 
            'wheat1':'beige', 
            'wheat2':'beige', 
            'wheat3':'marron', 
            'wheat4':'marron', 
            'white': 'blanc',  
            'white smoke':'blanc',   
            'yellow':'jaune', 
            'yellow jaune':'',
            'yellow2':'jaune', 
            'yellow3':'jaune', 
            'yellow4':'jaune', 
            




            }















