DICO_COIF = {'draggable':'coupe1',
            'draggable3':'coupe4',
            'draggable4':'coupe5',
            'draggable5':'coupe6',
            'draggable6':'coupe2',
            'draggable7':'coupe22',
            'draggable8':'coupe8',
            'draggable9':'coupe9',
            'draggable10':'coupe12',
            'draggable11':'coupe13',
            'draggable12':'coupe14',
            'draggable14':'coupe16',
            'draggable15':'coupe17',
            'draggable16':'coupe18',
            'draggable17':'coupe19',
            'draggable18':'coupe20',
            'draggable19':'coupe21'
             }


DICO_COIF2 = {'coupe1':'bbbbbbb.png',
            'coupe4':'image849849849.png',
            'coupe5':'bbbbbbb.png',
            'coupe6':'1.5.png',
            'coupe2':'coucou3.png',
            'coupe22':'coupe22.png',
            'coupe8':'coucou22.png',
            'coupe9':'coif.png',
            'coupe12':'aa.png',
            'coupe13':'aaaaa.png',
            'coupe14':'bb.png',
            'coupe16':'bbbb.png',
            'coupe17':'bbb.png',
            'coupe18':'1.1.png',
            'coupe19':'1.2.png',
            'coupe20':'11.3.png',
            'coupe21':'1.4.png'
             }
