DICO_COIF = {'draggable':'coupe1',
            'draggable3':'coupe4',
            'draggable4':'coupe5',
            'draggable5':'coupe6',
            'draggable6':'coupe2',
            'draggable7':'coupe22',
            'draggable8':'coupe8',
            'draggable9':'coupe9',
            'draggable10':'coupe12',
            'draggable11':'coupe13',
            'draggable12':'coupe14',
            'draggable14':'coupe16',
            'draggable15':'coupe17',
            'draggable16':'coupe18',
            'draggable17':'coupe19',
            'draggable18':'coupe20',
            'draggable19':'coupe21'}
