dico = {'alice blue':'bleu',
        'antique white':'beige',
        'AntiqueWhite1':'beige',
        'AntiqueWhite2':'marron beige',
        'AntiqueWhite3':'marron',
        'AntiqueWhite4':'',
        'aquamarine':'marron gris',
        'aquamarine2':'vert',
        'aquamarine4':'vert',
        'azure':'bleu clair',
        'azure2':'bleu',
        'azure3':'bleu',
        'azure4':'gris',
        'beige':'jaune',
        'bisque':'orange',
        'bisque2':'beige',
        'bisque3':'marron',
        'bisque4':'marron',
        'black':'noir',
        'blanched almond':'beige',
        'blue':'bleu',
        'blue violet':'bleu violet',
        'blue2':'bleu',
        'blue4':'bleu',
        'brown':'marron',
        'brown1':'marron',
        'brown2':'marron',
        'brown3':'marron',
        'brown4':'marron',
        'burlywood':'beige foncé',
        'burlywood1':'beige',
        'burlywood2':'beige',
        'burlywood3':'beige foncé',
        'burlywood4':'marron',
        'cadet blue':'bleu',
        'CadetBlue1':'bleu',
        'CadetBlue2':'bleu',
        'CadetBlue3':'bleu',
        'CadetBlue4':'bleu',
        'chartreuse':'vert',
        'chartreuse2':'vert',
        'chartreuse3':'vert',
        'chartreuse4':'vert',
        'chocolate':'marron',
        'chocolate1':'marron',
        'chocolate2':'marron',
        'chocolate3':'marron',
        'coral':'orange',
        'coral1':'orange',
        'coral2':'orange',
        'coral3':'orange',
        'coral4':'marron',
        'cornflower blue':'bleu',
        'cornsilk':'blanc',
        'cornsilk2':'blanc',
        'cornsilk3':'gris',
        'cornsilk4':'',
        'cyan':'gris',
        'cyan2':'bleu',
        'cyan3':'bleu',
        'cyan4':'vert',
        'dark goldenrod':'marron',
        'dark green':'vert',
        'dark grey':'gris',
        'dark khaki':'kaki',
        'dark olive green':'vert foncé',
        'dark orange':'orange foncé',
        'dark orchid':'violet',
        'dark salmon':'beige',
        'dark sea green':'vert',
        'dark slate blue':'bleu',
        'dark slate gray':'gris',
        'dark turquoise':'bleu',
        'dark viole':'violet',
        'DarkGoldenrod1':'jaune',
        'DarkGoldenrod2':'jaune',
        'DarkGoldenrod3':'jaune foncé',
        'DarkGoldenrod4':'marron',
        'DarkOliveGreen1':'vert',
        'DarkOliveGreen2':'vert',
        'DarkOliveGreen3':'vert',
        'DarkOliveGreen4':'vert foncé',
        'DarkOrange1':'orange',
        'DarkOrange2':'orange',
        'DarkOrange3':'orange',
        'DarkOrange4':'marron',
        'DarkOrchid1':'violet',
        'DarkOrchid2':'violet',
        'DarkOrchid3':'violet',
        'DarkOrchid4':'violet',
        'DarkSeaGreen1':'vert',
        'DarkSeaGreen2':'vert',
        'DarkSeaGreen3':'vert',
        'DarkSeaGreen4':'vert',
        'DarkSlateGray1':'turquoise',
        'DarkSlateGray2':'bleu',
        'DarkSlateGray3':'bleu',
        'DarkSlateGray4':'vert',
        'deep pink':'rose',
        'deep sky blue':'bleu,
        'DeepPink2':'',
        'DeepPink3':'',
        'DeepPink4':'',
        'DeepSkyBlue2':'',
        'DeepSkyBlue3':'',
        'DeepSkyBlue4':'',
        'dim gray':'',
        'dodger blue':'',
        'DodgerBlue2':'',
        'DodgerBlue3':'',
        'DodgerBlue4':'',
        'firebrick':'',
        'firebrick1':'',
        'firebrick2':'',
        'firebrick3':'',
        'firebrick4':'',
        'floral white':'',
        'forest green':'',
        'gainsboro':'',
        'ghost white':'',
        'gold':'',
        'gold2':'',
        'gold3':'',
        'gold4':'',
        'goldenrod':'',
        'goldenrod1':'',
        'goldenrod2':'',
        'goldenrod3':'',
        'goldenrod4':'',
        'gray':'',
        'gray1':'',
        'gray10':'',
        'gray11':'',
        'gray12':'',
        'gray13':'',
        'gray14':'',
        'gray15':'',
        'gray16':'',
        'gray17':'',
        'gray18':'',
        'gray19':'',
        'gray2':'',
        'gray20':'',
        'gray21':'',
        'gray22':'',
        'gray23':'',
        'gray24':'',
        'gray25':'',
        'gray26':'',
        'gray27':'',
        'gray28':'',
        'gray29':'',
        'gray3':'',
        'gray30':'',
        'gray31':'',
        'gray32':'',
        'gray33':'',
        'gray34':'',
        'gray35':'',
        'gray36':'',
        'gray37':'',
        'gray38':'',
        'gray39':'',
        'gray4':'',
        'gray40':'',
        'gray42':'',
        'gray43':'',
        'gray44':'',
        'gray45':'',
        'gray46':'',
        'gray47':'',
        'gray48':'',
        'gray49':'',
        'gray5':'',
        'gray50':'',
        'gray51':'',
        'gray52':'',
        'gray53':'',
        'gray54':'',
        'gray55':'',
        'gray56':'',
        'gray57':'',
        'gray58':'',
        'gray59':'',
        'gray6':'',
        'gray60':'',
        'gray61':'',
        'gray62':'',
        'gray63':'',
        'gray64':'',
        'gray65':'',
        'gray66':'',
        'gray67':'',,
        'gray68':'',
        'gray69':'',
        'gray7':'',
        'gray70':'',
        'gray71':'',
        'gray72':'',
        'gray73':'',
        'gray74':'',
        'gray75':'',
        'gray76':'',
        'gray77':'',
        'gray78':'',
        'gray79':'',
        'gray8':'',
        'gray80':'',
        'gray81':'',
        'gray82':'',
        'gray83':'',
        'gray84':'',
        'gray85':'',
        'gray86':'',
        'gray87':'',
        'gray88':'',
        'gray89':'',
        'gray9':'',
        'gray90':'',
        'gray91':'',
        'gray92':'',
        'gray93':'',
        'gray94':'',
        'gray95':'',
        'gray96':'',
        'gray97':'',,
        'gray98':'',
        'gray99':'',
        'green':'',
        'green yellow':'', 
        'green2':'', 
        'green3':'', 
        'green4':'', 
        'honeydew':'', 
        'honeydew2':'', 
        'honeydew3':'', 
        'honeydew4':'', 
        'hot pink':'', 
        'HotPink1':'', 
        'HotPink2':'', 
        'HotPink3':'', 
        'HotPink4':'', 
        'indian red':'',
        'IndianRed1':'', 
        'IndianRed2':'', 
        'IndianRed3':'', 
        'IndianRed4':'', 
        'ivory':'', 
        'ivory2':'', 
        'ivory3':'', 
        'ivory4':'', 
        'khaki':'', 
        'khaki1':'', 
        'khaki2':'', 
        'khaki3':'', 
        'khaki4':'', 
        'lavender':'', 
        'lavender blush':'', 
        'LavenderBlush2':'', 
        'LavenderBlush3':'', 
        'LavenderBlush4':'', 
        'lawn green':'', 
        'lemon chiffon':'', 
        'LemonChiffon2':'', 
        'LemonChiffon3':'', 
        'LemonChiffon4':'', 
        'light blue':'',
        'light coral':'', 
        'light cyan':'',
        'light goldenrod':'',
        'light goldenrod yellow':'',
        'light grey':'',  
        'light pink':'', 
        'light salmon': '', 
        'light sea green':'', 
        'light sky blue':'', 
        'light slate blue':'', 
        'light slate gray':'',     
        'light steel blue':'', 
        'light yellow': '',  
        'LightBlue1':'', 
        'LightBlue2':'', 
        'LightBlue3':'', 
        'LightBlue4':'', 
        'LightCyan2':'', 
        'LightCyan3':'', 
        'LightCyan4':'', 
        'LightGoldenrod1':'', 
        'LightGoldenrod2':'', 
        'LightGoldenrod3':'', 
        'LightGoldenrod4':'', 
        'LightPink1':'', 
        'LightPink2':'', 
        'LightPink3':'', 
        'LightPink4':'', 
        'LightSalmon2':'',
        'LightSalmon3':'',
        'LightSalmon4':'',
        'LightSkyBlue1':'',
        'LightSkyBlue2':'',
        'LightSkyBlue3':'',
        'LightSkyBlue4':'',
        'LightSteelBlue1':'',
        'LightSteelBlue2':'',
        'LightSteelBlue3':'',
        'LightSteelBlue4':'',
        'LightYellow2':'', 
        'LightYellow3':'', 
        'LightYellow4':'', 
        'lime green':''
        'linen':'', 
        'magenta':'',
        'magenta2':'',
        'magenta3':'',
        'magenta4':'',
        'maroon':'',
        'maroon1':'',
        'maroon2':'',
        'maroon3':'',
        'maroon4':'',
        'medium aquamarine':'',
        'medium blue':'',
        'medium orchid':'',
        'medium purple':'',
        'medium sea green':'',
        'medium slate blue':'',
        'medium spring green':'',
        'medium turquoise':'',
        'medium violet red':'',
        'MediumOrchid1':'',
        'MediumOrchid2':'',
        'MediumOrchid3':'',
        'MediumOrchid4':'',
        'MediumPurple1':'',
        'MediumPurple2':'',
        'MediumPurple3':'',
        'MediumPurple4':'', 
        'midnight blue':'',
        'misty rose':'',
        'MistyRose2':'',
        'MistyRose3':'',
        'MistyRose4':'',
        'moccasin':'',
        'navajo white':'',
        'NavajoWhite2':'',
        'NavajoWhite3':'',
        'NavajoWhite4':'',
        'navy':'',
        'old lace':'',
        'olive drab':'',
        'OliveDrab1':'',
        'OliveDrab2':'',
        'OliveDrab4':'',
        'orange':'',
        'orange red':'',
        'orange2':'',
        'orange3':'',
        'orange4':'',
        'OrangeRed2':'',
        'OrangeRed3':'',
        'OrangeRed4':'',
        'orchid':'',
        'orchid1':'',
        'orchid2':'',
        'orchid3':'',
        'orchid4':'',
        'pale goldenrod':'',
        'pale green':'',
        'pale turquoise':'',
        'pale violet red':'',
        'PaleGreen1':'',
        'PaleGreen2':'',
        'PaleGreen3':'',
        'PaleGreen4':'',
        'PaleTurquoise1':'',
        'PaleTurquoise2':'',
        'PaleTurquoise3':'',
        'PaleTurquoise4':'',
        'PaleVioletRed1':'',
        'PaleVioletRed2':'',
        'PaleVioletRed3':'',
        'PaleVioletRed4':'',
        'papaya whip':'',
        'peach puff':'',
        'PeachPuff2':'',
        'PeachPuff3':'',
        'PeachPuff4':'',
        'peru':'',
        'pink':'',
        'pink1':'',
        'pink2':'',
        'pink3':'',
        'pink4':'',
        'plum':'',
        'plum1':'',
        'plum2':'',
        'plum3':'',
        'plum4':'',
        'powder blue':'',
        'purple':'',
        'purple1':'',
        'purple2':'',
        'purple3':'',
        'purple4':'',
        'red':'',
        'red2':'',
        'red3':'',
        'red4':'',
        'rosy brown':'',
        'RosyBrown1':'',
        'RosyBrown2':'',
        'RosyBrown3':'',
        'RosyBrown4':'',
        'royal blue':'',
        'RoyalBlue1':'',
        'RoyalBlue2':'',
        'RoyalBlue3':'',
        'RoyalBlue4':'',
        'saddle brown':'',
        'salmon':'',
        'salmon1':'',
        'salmon2':'',
        'salmon3':'',
        'salmon4':'',
        'sandy brown':'',
        'sea green':'',
        'SeaGreen1':'',
        'SeaGreen2':'',
        'SeaGreen3':'',
        'seashell':'',
        'seashell2':'',
        'seashell3':'',
        'seashell4':'',
        'sienna':'',
        'sienna1':'',
        'sienna2':'',
        'sienna3':'',
        'sienna4':'',
        'sky blue':'',
        'SkyBlue1':'',
        'SkyBlue2':'', 
        'SkyBlue3'', 
        'SkyBlue4':'', 
        'slate blue':'', 
        'slate gray':'', 
        'SlateBlue1':'', 
        'SlateBlue2':'', 
        'SlateBlue3':'', 
        'SlateBlue4':'', 
        'SlateGray1':'', 
        'SlateGray2':'', 
        'SlateGray3':'', 
        'SlateGray4':'bleu', 
        'snow':'blanc',
        'snow2':'gris', 
        'snow3':'gris', 
        'snow4':'gris', 
        'spring green':'vert',
        'SpringGreen2':'', 
        'SpringGreen3':'vertvert', 
        'SpringGreen4':'vert', 
        'steel blue':'bleu', 
        'SteelBlue1':'bleu', 
        'SteelBlue2':'bleu', 
        'SteelBlue3':'bleu', 
        'SteelBlue4':'bleu', 
        'tan':'beige', 
        'tan1':'marron', 
        'tan2':'marron', 
        'tan4':'marron', 
        'thistle':'violet', 
        'thistle1':'rose', 
        'thistle2':'violet', 
        'thistle3':'violet', 
        'thistle4':'violet', 
        'tomato':'orange', 
        'tomato2':'orange', 
        'tomato3':'orange', 
        'tomato4':'marron', 
        'turquoise':'turquoise', 
        'turquoise1':'turquoise', 
        'turquoise2':'turquoise', 
        'turquoise3':'turquoise', 
        'turquoise4':'turquoise', 
        'violet':'violet', 
        'violet red':'violet rouge', 
        'VioletRed1':'violet rouge', 
        'VioletRed2':'violet rouge', 
        'VioletRed3':'violet rouge', 
        'VioletRed4':'violet rouge', 
        'wheat':'beige', 
        'wheat1':'beige', 
        'wheat2':'beige', 
        'wheat3':'marron beige', 
        'wheat4':'marron', 
        'white': 'blanc',  
        'white smoke':'blanc',   
        'yellow':'jaune', 
        'yellow jaune':'',
        'yellow2':'jaune', 
        'yellow3':'jaune', 
        'yellow4':'jaune', 
        




        }
